// <auto-generated />
using System;
using Infrastructure.Implementation.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Implementation.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250206111739_Add_Books")]
    partial class Add_Books
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaptersCount")
                        .HasColumnType("integer")
                        .HasColumnName("chapters_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string[]>("TitleVariants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("title_variants");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -70,
                            ChaptersCount = 50,
                            Title = "Бытие",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -1,
                            ChaptersCount = 40,
                            Title = "Исход",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -2,
                            ChaptersCount = 27,
                            Title = "Левит",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -3,
                            ChaptersCount = 36,
                            Title = "Числа",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -4,
                            ChaptersCount = 34,
                            Title = "Второзаконие",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -5,
                            ChaptersCount = 24,
                            Title = "Иисус Навин",
                            TitleVariants = new[] { "Иисуса Навина", "Иисуса Навин" }
                        },
                        new
                        {
                            Id = -6,
                            ChaptersCount = 21,
                            Title = "Судей",
                            TitleVariants = new[] { "Книга Судей" }
                        },
                        new
                        {
                            Id = -7,
                            ChaptersCount = 4,
                            Title = "Руфь",
                            TitleVariants = new[] { "Руфи" }
                        },
                        new
                        {
                            Id = -8,
                            ChaptersCount = 31,
                            Title = "1-Царств",
                            TitleVariants = new[] { "Первая Царств", "1 Царств" }
                        },
                        new
                        {
                            Id = -9,
                            ChaptersCount = 24,
                            Title = "2-Царств",
                            TitleVariants = new[] { "Вторая Царств", "2 Царств" }
                        },
                        new
                        {
                            Id = -10,
                            ChaptersCount = 22,
                            Title = "3-Царств",
                            TitleVariants = new[] { "Третья Царств", "3 Царств" }
                        },
                        new
                        {
                            Id = -11,
                            ChaptersCount = 25,
                            Title = "4-Царств",
                            TitleVariants = new[] { "Четвёртая Царств", "4 Царств" }
                        },
                        new
                        {
                            Id = -12,
                            ChaptersCount = 29,
                            Title = "1-Паралипоменон",
                            TitleVariants = new[] { "Первая Паралипоменон", "1 Пар", "1 Паралипоменон" }
                        },
                        new
                        {
                            Id = -13,
                            ChaptersCount = 36,
                            Title = "2-Паралипоменон",
                            TitleVariants = new[] { "Вторая Паралипоменон", "2 Пар", "2 Паралипоменон" }
                        },
                        new
                        {
                            Id = -14,
                            ChaptersCount = 10,
                            Title = "Ездра",
                            TitleVariants = new[] { "Ездры" }
                        },
                        new
                        {
                            Id = -15,
                            ChaptersCount = 13,
                            Title = "Неемия",
                            TitleVariants = new[] { "Неемии" }
                        },
                        new
                        {
                            Id = -16,
                            ChaptersCount = 10,
                            Title = "Есфирь",
                            TitleVariants = new[] { "Есфири" }
                        },
                        new
                        {
                            Id = -17,
                            ChaptersCount = 42,
                            Title = "Иов",
                            TitleVariants = new[] { "Иова" }
                        },
                        new
                        {
                            Id = -18,
                            ChaptersCount = 150,
                            Title = "Псалтирь",
                            TitleVariants = new[] { "Псалмы", "Псалом" }
                        },
                        new
                        {
                            Id = -19,
                            ChaptersCount = 31,
                            Title = "Притчи",
                            TitleVariants = new[] { "Притчи Соломона" }
                        },
                        new
                        {
                            Id = -20,
                            ChaptersCount = 12,
                            Title = "Екклесиаст",
                            TitleVariants = new[] { "Екклесиаста", "Экклезиаст" }
                        },
                        new
                        {
                            Id = -21,
                            ChaptersCount = 8,
                            Title = "Песни Песней",
                            TitleVariants = new[] { "Песнь Соломона" }
                        },
                        new
                        {
                            Id = -22,
                            ChaptersCount = 66,
                            Title = "Исаия",
                            TitleVariants = new[] { "Исайя" }
                        },
                        new
                        {
                            Id = -23,
                            ChaptersCount = 52,
                            Title = "Иеремия",
                            TitleVariants = new[] { "Иеремии" }
                        },
                        new
                        {
                            Id = -24,
                            ChaptersCount = 5,
                            Title = "Плач Иеремии",
                            TitleVariants = new string[0]
                        },
                        new
                        {
                            Id = -25,
                            ChaptersCount = 48,
                            Title = "Иезекииль",
                            TitleVariants = new[] { "Иезекииля" }
                        },
                        new
                        {
                            Id = -26,
                            ChaptersCount = 12,
                            Title = "Даниил",
                            TitleVariants = new[] { "Даниила" }
                        },
                        new
                        {
                            Id = -27,
                            ChaptersCount = 14,
                            Title = "Осия",
                            TitleVariants = new[] { "Осии" }
                        },
                        new
                        {
                            Id = -28,
                            ChaptersCount = 3,
                            Title = "Иоиль",
                            TitleVariants = new[] { "Иоиля" }
                        },
                        new
                        {
                            Id = -29,
                            ChaptersCount = 9,
                            Title = "Амос",
                            TitleVariants = new[] { "Амоса" }
                        },
                        new
                        {
                            Id = -30,
                            ChaptersCount = 1,
                            Title = "Авдий",
                            TitleVariants = new[] { "Авдия" }
                        },
                        new
                        {
                            Id = -31,
                            ChaptersCount = 4,
                            Title = "Иона",
                            TitleVariants = new[] { "Ионы" }
                        },
                        new
                        {
                            Id = -32,
                            ChaptersCount = 7,
                            Title = "Михей",
                            TitleVariants = new[] { "Михея" }
                        },
                        new
                        {
                            Id = -33,
                            ChaptersCount = 3,
                            Title = "Наум",
                            TitleVariants = new[] { "Наума" }
                        },
                        new
                        {
                            Id = -34,
                            ChaptersCount = 3,
                            Title = "Аввакум",
                            TitleVariants = new[] { "Аввакума" }
                        },
                        new
                        {
                            Id = -35,
                            ChaptersCount = 3,
                            Title = "Софония",
                            TitleVariants = new[] { "Софонии" }
                        },
                        new
                        {
                            Id = -36,
                            ChaptersCount = 2,
                            Title = "Аггей",
                            TitleVariants = new[] { "Аггея" }
                        },
                        new
                        {
                            Id = -37,
                            ChaptersCount = 14,
                            Title = "Захария",
                            TitleVariants = new[] { "Захарии" }
                        },
                        new
                        {
                            Id = -38,
                            ChaptersCount = 4,
                            Title = "Малахия",
                            TitleVariants = new[] { "Малахии" }
                        },
                        new
                        {
                            Id = -39,
                            ChaptersCount = 28,
                            Title = "Матфея",
                            TitleVariants = new[] { "Матвея" }
                        },
                        new
                        {
                            Id = -40,
                            ChaptersCount = 16,
                            Title = "Марка",
                            TitleVariants = new[] { "Марка" }
                        },
                        new
                        {
                            Id = -41,
                            ChaptersCount = 24,
                            Title = "Луки",
                            TitleVariants = new[] { "Луки" }
                        },
                        new
                        {
                            Id = -42,
                            ChaptersCount = 21,
                            Title = "Иоанна",
                            TitleVariants = new[] { "Иоана" }
                        },
                        new
                        {
                            Id = -43,
                            ChaptersCount = 28,
                            Title = "Деяния",
                            TitleVariants = new[] { "Деяния Апостолов" }
                        },
                        new
                        {
                            Id = -44,
                            ChaptersCount = 5,
                            Title = "Иакова",
                            TitleVariants = new[] { "Послание Иакова" }
                        },
                        new
                        {
                            Id = -45,
                            ChaptersCount = 5,
                            Title = "1-Петра",
                            TitleVariants = new[] { "Первое Петра", "1 Петра" }
                        },
                        new
                        {
                            Id = -46,
                            ChaptersCount = 3,
                            Title = "2-Петра",
                            TitleVariants = new[] { "Второе Петра", "2 Петра" }
                        },
                        new
                        {
                            Id = -47,
                            ChaptersCount = 5,
                            Title = "1-Иоанна",
                            TitleVariants = new[] { "Первое Иоанна", "1 Иоанна" }
                        },
                        new
                        {
                            Id = -48,
                            ChaptersCount = 1,
                            Title = "2-Иоанна",
                            TitleVariants = new[] { "Второе Иоанна", "2 Иоанна" }
                        },
                        new
                        {
                            Id = -49,
                            ChaptersCount = 1,
                            Title = "3-Иоанна",
                            TitleVariants = new[] { "Третье Иоанна", "3 Иоанна" }
                        },
                        new
                        {
                            Id = -50,
                            ChaptersCount = 1,
                            Title = "Иуды",
                            TitleVariants = new[] { "Послание Иуды" }
                        },
                        new
                        {
                            Id = -51,
                            ChaptersCount = 16,
                            Title = "Римлянам",
                            TitleVariants = new[] { "Римлянам" }
                        },
                        new
                        {
                            Id = -52,
                            ChaptersCount = 16,
                            Title = "1-Коринфянам",
                            TitleVariants = new[] { "Первое Коринфянам", "1 Коринфянам" }
                        },
                        new
                        {
                            Id = -53,
                            ChaptersCount = 13,
                            Title = "2-Коринфянам",
                            TitleVariants = new[] { "Второе Коринфянам", "2 Коринфянам" }
                        },
                        new
                        {
                            Id = -54,
                            ChaptersCount = 6,
                            Title = "Галатам",
                            TitleVariants = new[] { "Галатам" }
                        },
                        new
                        {
                            Id = -55,
                            ChaptersCount = 6,
                            Title = "Ефесянам",
                            TitleVariants = new[] { "Ефесянам" }
                        },
                        new
                        {
                            Id = -56,
                            ChaptersCount = 4,
                            Title = "Филиппийцам",
                            TitleVariants = new[] { "Филиппийцам" }
                        },
                        new
                        {
                            Id = -57,
                            ChaptersCount = 4,
                            Title = "Колоссянам",
                            TitleVariants = new[] { "Колоссянам" }
                        },
                        new
                        {
                            Id = -58,
                            ChaptersCount = 5,
                            Title = "1-Фессалоникийцам",
                            TitleVariants = new[] { "Первое Фессалоникийцам", "1 Фессалоникийцам" }
                        },
                        new
                        {
                            Id = -59,
                            ChaptersCount = 3,
                            Title = "2-Фессалоникийцам",
                            TitleVariants = new[] { "Второе Фессалоникийцам", "2 Фессалоникийцам" }
                        },
                        new
                        {
                            Id = -60,
                            ChaptersCount = 6,
                            Title = "1-Тимофею",
                            TitleVariants = new[] { "Первое Тимофею", "1 Тимофею" }
                        },
                        new
                        {
                            Id = -61,
                            ChaptersCount = 4,
                            Title = "2-Тимофею",
                            TitleVariants = new[] { "Второе Тимофею", "2 Тимофею" }
                        },
                        new
                        {
                            Id = -62,
                            ChaptersCount = 3,
                            Title = "Титу",
                            TitleVariants = new[] { "Титу" }
                        },
                        new
                        {
                            Id = -63,
                            ChaptersCount = 1,
                            Title = "Филимону",
                            TitleVariants = new[] { "Филимону" }
                        },
                        new
                        {
                            Id = -64,
                            ChaptersCount = 13,
                            Title = "Евреям",
                            TitleVariants = new[] { "Евреям" }
                        },
                        new
                        {
                            Id = -65,
                            ChaptersCount = 22,
                            Title = "Откровение",
                            TitleVariants = new[] { "Апокалипсис", "Откровение Иоанна" }
                        });
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReadEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("EndChapter")
                        .HasColumnType("integer")
                        .HasColumnName("end_chapter");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint")
                        .HasColumnName("participant_id");

                    b.Property<int>("StartChapter")
                        .HasColumnType("integer")
                        .HasColumnName("start_chapter");

                    b.HasKey("Id")
                        .HasName("pk_read_entries");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_read_entries_book_id");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_read_entries_participant_id");

                    b.ToTable("read_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReadEntry", b =>
                {
                    b.HasOne("Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_read_entries_books_book_id");

                    b.HasOne("Domain.Entities.Participant", "Participant")
                        .WithMany("ReadEntries")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_read_entries_participants_participant_id");

                    b.Navigation("Book");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Navigation("ReadEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
